server:
  port: 8081
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl?characterEncoding=UTF-8
    username: skuser
    password: skuser
mybatis:
  type-aliases-package: com.sk.study.demo.springcloud.simple.user.model