server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl?characterEncoding=UTF-8
    username: skuser
    password: skuser
mybatis:
  type-aliases-package: com.sk.study.demo.springcloud.simple.user.model
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka